Numeric planning
plaans/aries pull request #105
Opened 2023-10-19 12:46 UTC by Shi-Raida

Refactoring and fixing some bugs on resource constraints encoding.

2023-10-19 12:49 UTC, arbimo requested changes
This includes the code for PR #104 that is not ready yet (awaiting the corresponding PR to be merged in UP)

2023-10-27 16:01 UTC, arbimo requested changes
This looks good to me. I have just pointed out a few very minor changes and I think it can be merge directly when this is fixed :)

2023-10-27 16:01 UTC, arbimo commented on planning/planners/src/encode.rs
> +    let eff_assign_ends: HashMap<EffID, FVar> = effs
I don't understand why this one needs to be different from the one above. Essentially if you use the second one, you don't use the first. So use the first all the time =)

2023-10-27 16:01 UTC, arbimo commented on planning/planners/src/encode.rs
> +            match solver.propagate() {
Exactly the same thing is done in both branches.

2023-10-27 16:01 UTC, arbimo commented on planning/planners/src/encode.rs
> +            (INT_CST_MIN, INT_CST_MAX)
Shouldn't this be a panic t o be consistent with the above ? If it is not of type Int it is a bug that we arrived at this point.

2023-10-27 16:01 UTC, arbimo commented on planning/planners/src/encode.rs
> +     * With all these literals, only one constraint will be taken into account: that associated with the last assignment.
```suggestion
     * With all these literals, only one constraint will be taken into account: the one associated with the last assignment.
```

2023-10-27 16:01 UTC, arbimo commented on planning/planners/src/encode.rs
> +        // Whether the effect is likely to support the condition.
```suggestion
        // Returns false if the effect can never support the condition.
```

2023-10-27 16:01 UTC, arbimo commented on planning/planning/src/chronicles/mod.rs
> +    AssignEnd,
Same as above, can probably be merge with effect end, they really serve the same purpose.

2023-10-27 16:01 UTC, arbimo commented on solver/src/reif/mod.rs
> +                write!(f, "{md:?}")
More explicit ? (max diff is already not very common)

2023-11-06 14:04 UTC, Shi-Raida commented on solver/src/reif/mod.rs
> +                write!(f, "{md:?}")
The `Debug` implementation of `DifferenceExpression` (`md`) writes `b <= a + ub`.
Isn't it enough?

2023-11-06 14:28 UTC, arbimo commented on solver/src/reif/mod.rs
> +                write!(f, "{md:?}")
Yes, I misread the `write`.

2023-11-06 14:43 UTC, arbimo commented
LGTM. Could you merge the latest master in this branch?
Changes in master related to testing should take precedence over the ones in this PR.

2023-11-06 14:58 UTC, arbimo approved these changes

2023-11-06 14:59 UTC, merged

2023-11-06 15:04 UTC, Shi-Raida commented
> > Four problems crash on Anytime but I don't have logs from Aries so it doesn't start
> 
> Most likely unrelated to this PR, I suspect that the code for checking the correctness of anytime planners does not support scheduling problems.

Yes, I find in `planning/unified/plugin/up_aries/solver.py` line 340:

``` python
assert isinstance(problem, up.model.Problem)
```

The four problems are `SchedulingProblem` which does not inherit from `Problem`.
I'll open a new branch to fix it.