Assumption solving #20
plaans/aries pull request #159
Opened 2024-12-29 18:05 UTC by nrealus

2025-01-08 15:56 UTC, arbimo requested changes
@nrealus I have made several improvements mostly targeted at making it the API more flexible and making it hard to misuses it.

There are some fairly wide changes as a result of updating some method names to better reflect their current semantic.

The changes notably allow to detect a bug in your tests (extracting an unsat core on a conflict involving a decision). This should be fixed but otherwise the code looks good to me.

As a general feedback, it would be good to provide more comment on the code provide. Both on the methods themselves (purpose and assumptions) as well as in the code (to justify why non-obvious operations are done).

2025-01-08 17:00 UTC, nrealus commented
@arbimo Thank you for the improvements ! They do make everything much more robust and understandable. I wouldn't have taken the risk to modify these core parts of the code by myself. Also thank you for the feedback. It should be easier to make comments in the new features I'm working on currently, since they are new features that do not modify the solver's core. (mus/mcs enumeration, explanations).

However, I do have a question (related to the failing unit test). Suppose literal `!h` was propagated as a result of two assumptions. Now, suppose that during the search, the solver decides to set literal `g` (which implies literal `h`, due a to a constraint). This decision, after propagation, results in a `InvalidUpdate` on `h`. How does this relate to the documentation of `clause_for_invalid_inferrence`, which states "The update of `l` must not directly originate from a decision as it is necessarily the case that `l` holds in the current state. It is thus considered a logic error to impose an obviously wrong decision." Does the example above fall into this situation, or not ? To me, it seems that it does not fall into this situation, but I am not sure

2025-01-08 18:42 UTC, nrealus commented
@arbimo Question: How should we enable incremental solving ? For example, we first want to solve to see if the problem is SAT with `a`, `b`, `c`, and then (if SAT) we want to further see if it is SAT with `a`, `b`, `c`, `d`, and `e`. But we want to avoid doing assumption and propagation work for literals `a`, `b`, `c` twice, and also want to avoid cloning the solver / model in the intermediate state and only then solve for just `d` and `e`. (Basically "pick up" the solving from the state after assuming and propagating `a`, `b`, `c`). The easiest way would be to allow backtracking to the last assumption level, and then launch `solve_with_assumptions`, but then, `solve_with_assumptions` should be allowed to run even if the decision level is not root. What do you think about this ?

2025-01-09 08:36 UTC, arbimo commented
@nrealus I'll merge this as it is and we can make further improvements in a follow up PR.


Regarding your question.
First, user facing methods should return an UNSAT core instead of the current conflict in hte UNSAT case.
This is much more useful in general (and one can still reach for lower level primitives if more control is needed).


Incremental solving should be something like that (imagine it in a repl, with commands like the ones you have in SMT solvers). Relying on finer grained methods (notably the ones I added in the first commit).

```
> push(a)   (~ assume_and_propagate(a))
Ok -- assumptions: a

> push(b)  (~ assume_and_propagate(b))
Ok -- assumptions: a, b

> solve (~search())
KO, unsat core {b}

> pop  (reset_search() + restore_last())
Ok -- assumptions: a

> push(c)  (~ assume and propagate(c))
Ok -- assumptions: a, c

-> solve
Ok
```

If we are to keep it, `solve_with_assumptions should only be a convenience method when you want an unsat core for some assumptions but are not interested in incremental solving.

All the lower level primitives in the example should already work with assumptions on the stack (also from the first commit I added). The the more abstract methods (solve, optimize, sole_with assumption, ...) probably require some minor changes to support working on top of existing assumptions.

2025-01-09 08:37 UTC, arbimo approved these changes

2025-01-09 08:37 UTC, merged

2025-01-09 12:55 UTC, nrealus commented
Oh right. I remember now that this is how it's done in Z3 (among others).

Side node for later: A (seemingly easy) thing that we should later allow is to make all (or a given number of) assumptions at once, and only then propagate them. This is suggested by [1] and is used in OR-Tools [2]

[1][Hickey and Bacchus (2019) Speeding Up Assumption-Based SAT](http://www.cs.toronto.edu/~fbacchus/csc2512/Readings/Hickey-Bacchus2019_Chapter_SpeedingUpAssumption-BasedSAT.pdf)
[2][See `ResetWithGivenAssumptions` documentation snippet](https://developers.google.com/optimization/reference/sat/sat_solver/SatSolver)

2025-01-09 14:29 UTC, arbimo commented
> Oh right. I remember now that this is how it's done in Z3 (among others).
> 
> Side note for later: A (seemingly easy) thing that we should later allow is to make all (or a given number of) assumptions at once, and only then propagate them. This is suggested by [1] and is used in OR-Tools [2]
> 
> [1][Hickey and Bacchus (2019) Speeding Up Assumption-Based SAT](http://www.cs.toronto.edu/~fbacchus/csc2512/Readings/Hickey-Bacchus2019_Chapter_SpeedingUpAssumption-BasedSAT.pdf) [2][See `ResetWithGivenAssumptions` documentation snippet](https://developers.google.com/optimization/reference/sat/sat_solver/SatSolver)

Agreed that it would be really nice to have and may in fact simplify the implementation even more (we would only have a single decision level for assumptions (`DecLvl::Assumptions`).

Regarding trail saving:
 - to avoid redundant work when backtracking to root because of a unit clause, we already have a propagator (tautologies) that avoid backtracking altogether
 - for reusing propagation from a previous set of assumption, implementation is non trivial because we would need to pre-compute the reason of all literals in the trail (while a pure SAT solver already has the ID of the clause that propagated it