Minor Refactoring to LCP
plaans/aries pull request #32
Opened 2022-03-07 16:44 UTC by franklinselva

2022-03-08 07:59 UTC, franklinselva commented on planners/src/solver.rs
> +use aries_model::state::Domains;
Possibility of missing `state.rs` in `master` branch.

https://github.com/plaans/aries/tree/master/model/src

2022-03-08 07:59 UTC, franklinselva commented on planners/src/solver.rs
> +use aries_model::state::Domains;
Possibility of missing `state.rs` in `master` branch.

https://github.com/plaans/aries/tree/master/model/src

2022-03-08 08:01 UTC, franklinselva commented on planners/src/solver.rs
> +            plan: None,
`plan: None` -> Only builds in local machines

2022-03-08 08:56 UTC, arbimo commented
All pull requests should be based on the master branch. Could you rebase this ?

Also, to avoid any unhandled lints, you should make sure that you have the latest rust version (`rustup update`).

2022-03-08 11:44 UTC, franklinselva commented
> All pull requests should be based on the master branch. Could you rebase this ?
> 
> Also, to avoid any unhandled lints, you should make sure that you have the latest rust version (`rustup update`).

I will rebase the changes from `temporal-pddl` branch.

The RUST has been updated and the version is `1.59.0`. I will check for the issue

2022-03-09 09:52 UTC, franklinselva commented
Adding PR #24 to address rebase issue.

2022-03-20 21:45 UTC, arbimo requested changes
@franklinselva I corrected the bug you had. It was caused by the reuse of the base problem which resulted in an exponential growth in its size.

I made some comment on the existing implementation.
The overall idea is to simplify the implementation to only have a couple of state-less functions with explicit parameters (instead of the `Opt` that is specific to LCP and is bound to grow over time).

2022-03-20 21:45 UTC, arbimo commented on planners/src/solver.rs
> +pub struct Opt {
This should stay in the lcp.rs file.

2022-03-20 21:45 UTC, arbimo commented on planners/src/solver.rs
> +pub struct Planner {
There is no reason for the Planner to be stateful. It is probably better to only have a set of free-standing functions with well identified parameters. So the `Planner` struct should be removed and the method take their needed parameters explicitly.

2022-03-20 21:45 UTC, arbimo commented on planners/src/solver.rs
> +    pub fn solve(&mut self, mut spec: Problem, opt: &Opt) -> Result<()> {
Make a function: remove the `self` and pass needed parameters explicitly (breaking out the `Opt` into individual parameters). It should not have access to any uneeded information (e.g. the problem filename).

Could be renamed `deepening_solve`.

2022-03-20 21:45 UTC, arbimo commented on planners/src/solver.rs
> +            if let Some(plan_out_file) = self.option.plan_out_file.clone() {
Writing out the plan to a file should stay in the lcp.rs file.

2022-03-20 21:45 UTC, arbimo commented on planners/src/solver.rs
> +fn _solve(pb: &FiniteProblem, opt: &Opt, htn_mode: bool) -> Option<std::sync::Arc<SavedAssignment>> {
Rename `solve_finite_problem`. Split the `Opt` into several args.

2022-03-20 21:45 UTC, arbimo commented on planners/src/solver.rs
> +                            .clone()
I don't believe the clone to be useful there.

2022-03-20 21:45 UTC, arbimo commented on planners/src/solver.rs
> +                            .clone()
idem

2022-03-20 21:45 UTC, arbimo commented on planners/src/solver.rs
> +                        .clone()
idem

2022-03-20 21:45 UTC, arbimo commented on planners/src/solver.rs
> +        Ok(())
The plan should be returned (actually necessary without the `Planner` instance).

2022-03-20 21:45 UTC, arbimo commented on planners/src/solver.rs
> +    pub fn format_plan(&self, plan: &Option<Arc<Domains>>) -> Result<()> {
This performs many side effects and should probably remain in `lcp.rs`. The logic is actually quite simple and different `main` implementation are likely to want different behaviors anyway.

In general, the method name should have been `print_plan` as it does more than just formatting.

2022-03-21 21:30 UTC, merged