Compile UP protobuf definitions as feature
plaans/aries pull request #54
Opened 2022-11-15 12:05 UTC by franklinselva

The UP protobuf definitions can now be compiled at request as a `feature` through the following:

```bash
cargo build --features=unified_planning
```

2022-11-15 20:13 UTC, arbimo commented
That's an excellent idea!

To complete it, you should:
 - make the `tonic-build` dependency only active when the feature is enabled.
 - document this in a `grpc/api/README.md` file

2022-11-16 08:43 UTC, franklinselva commented
@arbimo  I have updated the dependencies and documentation for building the definitions. 

As a side note, this change allows the `up-server` to be cross compiled for windows platform.

2022-11-16 10:44 UTC, arbimo requested changes
Since it is not done systematically, the CI should also be updated to check that the unified_planning.rs file is up to date. 
This should be as simple as compiling the `grpc/api` crate with the feature enabled.

Finally the feature should have a more specific name, e.g., `generate_bindings`. (the whole crate is about unified planning).

2022-11-16 10:44 UTC, arbimo commented on grpc/README.md
> +## GRPC API
Just need to be a little more specific: generating the rust bindings (file XXXX) from the protobuf format definition (file XXX).

2022-11-16 11:18 UTC, franklinselva commented
The current bindings are slightly custom (with comments and formatting) and launching the CI might be failing at this stage. Shall we update the current bindings to the generated version?

The current differences when compiling bindings are available in the patch ([bindings.txt](https://github.com/plaans/aries/files/10021050/bindings.txt)).

2022-11-16 12:49 UTC, franklinselva commented on grpc/README.md
> +## GRPC API
I have updated the documentation for the `GRPC` crate

2022-11-16 14:31 UTC, arbimo approved these changes

2022-11-16 14:32 UTC, merged