CoHoMa: unsupported features
plaans/aries pull request #88
Opened 2023-03-28 12:22 UTC by Shi-Raida

2023-03-28 12:24 UTC, Shi-Raida commented on solver/src/core/variable.rs
I had to decrease the integer variable domains size because that was causing a memory overflow during `./ci/lcp.sh` run.

2023-03-31 08:24 UTC, Shi-Raida commented
Solving the UP problem `hddl:2020-to-Woodworking` is timed out by the CI. On my laptop it is crashing with the following error:

```
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'assertion failed: model.violated_clause(clause.clause_with_scope())assertion failed: model.violated_clause(clause.clause_with_scope())', ', solver/src/reasoners/sat/sat_solver.rssolver/src/reasoners/sat/sat_solver.rs:thread ':330<unnamed>330:' panicked at ':17assertion failed: model.violated_clause(clause.clause_with_scope())17
```

2023-04-27 12:13 UTC, arbimo requested changes
Looks good! I just just flagged a few minors things to fix before merging.

2023-04-27 12:13 UTC, arbimo commented on planning/grpc/server/src/chronicles.rs
> +            // TODO: optimize the case where durations are constant
Remove this TODO (handled in constraint posting)

2023-04-27 12:13 UTC, arbimo commented on planning/planners/src/encode.rs
> +                        let into_fatom = |value: Atom| match value {
Still incorrect: `(?x / 5) < 1 ` would result in `(?x / 5) < (1 / 10)` (where 10 is the TIME_SCALE).
It is ok not to support it but you should at least raise an error.

2023-04-27 12:13 UTC, arbimo commented on solver/src/core/variable.rs
This can be reverted now.

2023-04-27 12:13 UTC, arbimo commented on solver/src/model/lang/fixed.rs
> +
Remove both `Add<FAtom>` and `Sub<FAtom>` : the base case of these methods is to panic (different denom or different variable)

2023-04-27 12:13 UTC, arbimo commented on solver/src/model/lang/int.rs
> +
Idem: remove both implementations

2023-04-27 12:13 UTC, arbimo commented on solver/src/model/lang/linear.rs
> +    pub(crate) fn cleaner(&self) -> NFLinearLeq {
Could be renamed `simplified`

2023-04-27 12:13 UTC, arbimo commented on solver/src/solver/solver_impl.rs
> +                        assert_ne!(fst.factor, 0);
These could be `debug_assert_ne!`: no matter what input is thrown at the function, this can never happen (unless you have a bug in `cleaner`).

2023-04-27 12:57 UTC, arbimo approved these changes

2023-04-27 13:03 UTC, merged